// example/react/pages/hello.jsx
import { useState, useEffect } from 'react'
import { useServerAPI, useServerData } from 'fastify-vite/react/hooks'

export default async function Hello() {
  const [msg, setMsg] = useState(0);
  const api = useServerAPI()
  const [data, dataPath] = await useServerData()
  const state = reactive({ message: data?.message })

  const refreshData = async () => {
    const response = await fetch(dataPath)
    const json = await response.json()
    setMsg(json.message)
  }

  useEffect(() => {
    if (!data && !import.meta.env.SSR) {
      await refreshData()
    }
  })

  return (
    <h1 onClick={refreshData}>{msg}</h1>
  )
}

// example/pages/hello.vue
<template>
  <h1 @click="refreshData">{{ data.message }}</h1>
</template>

<script>
import { ref } from 'vue'
import { useSSRData } from 'fastify-vite/hooks'

export default {
  async setup () {
    const [ data, dataPath ] = useSSRData()
    const refreshData = async () => {
      const response = await fetch(dataPath)
      data.value = await response.json()
    }
    if (!data.value && !import.meta.env.SSR) {
      await refreshData()
    }
    return { data, refreshData }
  }
}
</script>

<style scoped>
h1 {
  cursor: pointer;
  color: red;
}
</style>
