// examples/react-api/views/index.jsx
import { Link } from 'react-router-dom'

export const path = '/'

export default function Index () {
  return (
    <>
      <ul>
        <li>
          <Link to="/global-data">Global Data</Link><span>:</span>
          <b>useHydration()</b> and <b>$global</b> data.
        </li>
        <li>
          <Link to="/route-hooks">Route Hooks</Link><span>:</span>
          <b>onRequest()</b>, <b>useHydration()</b> and <b>$data</b>.
        </li>
        <li>
          <Link to="/route-payload">Route Payload</Link><span>:</span>
          <b>useHydration()</b>, <b>getPayload()</b> and <b>$payloadPath</b>.
        </li>
        <li>
          <Link to="/data-fetching">Isomorphic API</Link><span>:</span>
          <b>useHydration()</b>, <b>getData()</b> and <b>$data</b>.
        </li>
      </ul>
    </>
  )
}

// examples/vue-api/views/index.vue
<template>
  <ul>
    <li>
      <router-link to="/global-data">Global Data</router-link><span>:</span>
      <b>useHydration()</b> and <b>$global</b> data.
    </li>
    <li>
      <router-link to="/route-hooks">Route Hooks</router-link><span>:</span>
      <b>onRequest()</b>, <b>useHydration()</b> and <b>$data</b>.
    </li>
    <li>
      <router-link to="/route-payload">Route Payload</router-link><span>:</span>
      <b>useHydration()</b>, <b>getPayload()</b> and <b>$payloadPath</b>.
    </li>
    <li>
      <router-link to="/data-fetching">Isomorphic API</router-link><span>:</span>
      <b>useHydration()</b>, <b>getData()</b> and <b>$data</b>.
    </li>
  </ul>
</template>

<script>
export const path = '/'
</script>
