// example/pages/hello.vue
<template>
  <h1 @click="refreshData">{{ data.message }}</h1>
</template>

<script>
import { ref } from 'vue'
import { useSSRData } from 'fastify-vite/hooks'

export default {
  async setup () {
    const [ data, dataPath ] = useSSRData()
    const refreshData = async () => {
      const response = await fetch(dataPath)
      data.value = await response.json()
    }
    if (!data.value && !import.meta.env.SSR) {
      await refreshData()
    }
    return { data, refreshData }
  }
}
</script>

<style scoped>
h1 {
  cursor: pointer;
  color: red;
}
</style>

// examples/react/pages/Hello.jsx
import { useState, useEffect } from 'react'
import { useSSEContext } from 'fastify-vite-react/client'

export default function Hello () {
  const { context, setContext } = useSSEContext()
  const [msg, setMsg] = useState(context?.$data?.message)

  const refreshData = async () => {
    const response = await fetch(context.$dataPath())
    const json = await response.json()
    setMsg(json.message)
  }

  useEffect(() => {
    if (!msg && !import.meta.env.SSR) {
      refreshData()
    }
  })

  return <h1 onClick={refreshData}>{msg}</h1>
}
