// examples/solid/client/entry/client.jsx
import { hydrate } from 'solid-js/web'
import createApp from './app.jsx'
import Context from './context.js'

const { Element, Router, routes } = createApp()

hydrate(
  <Context.Provider context={window.hydration}>  
    <Router>
      <Element routes={routes} />
    </Router>
  </Context.Provider>,
  document.querySelector('main'),  
)

// examples/react/client/entry/client.jsx
import { hydrateRoot } from 'react-dom/client'
import { createApp } from './app.jsx'
import Context from './context.js'

const { Element, Router, routes } = createApp()

hydrateRoot(
  document.querySelector('main'),
  <Context.Provider value={window.hydration}>  
    <Router>
      {Element(routes)}
    </Router>
  </Context.Provider>
)
