// starters/vue-base/client/pages/index.vue
<template>
  <h1>{{ message }}</h1>
  <p><img :src="logo" /></p>
</template>

<script setup>
import logo from '/assets/logo.svg'

const message = 'Welcome to @fastify/vue!'
</script>

<script>
export function getMeta() {
  return {
    title: 'Welcome to @fastify/vue!',
  }
}
</script>

<style scoped>
img {
  width: 100%;
}
</style>

// starters/react-base/client/pages/index.jsx
import logo from '/assets/logo.svg'

export function getMeta () {
  return {
    title: 'Welcome to @fastify/react!'
  }
}

export default function Index () {
  const message = 'Welcome to @fastify/react!'
  return (
    <>
      <p>{message}</p>
      <img style={{width: '100%'}} src={logo} />
    </>
  )
}
