// examples/svelte-hydration/client/views/index.svelte
<script>
import { Link } from 'svelte-routing'
export let data = null
</script>

<ul>
  {#each data.todoList as item, i}
    <li>{item}</li>
  {/each}
  </ul>
<div>
  <!--input ref={input} /-->
  <!--button onClick={addItem}>Add</button-->
</div>
<p>
  <Link to="/other">Go to another page</Link>
</p>

// examples/vue-hydration/client/views/index.vue
<template>
  <ul>
    <li
      v-for="(listItem, i) in state.todoList"
      :key="`item-${i}`">
      {{ listItem }}
    </li>
  </ul>
  <div>
    <input v-model="item">
    <button @click="addItem">
      Add
    </button>
  </div>
  <p>
    <router-link to="/other">
      Go to another page
    </router-link>
  </p>
</template>

<script>
export default {
  inject: ['state'],
  data: () => ({
    item: ''
  }),
  methods: {
    async addItem () {
      this.state.todoList.push(this.item)
      this.item = ''
    }
  }
}
</script>
