// starters/vue-kitchensink/client/layouts/auth.vue
<template>
  <div class="contents">
    <template v-if="!state.user.authenticated">
      <p>This route needs authentication.</p>
      <button @click="actions.authenticate(state)">Click this button to authenticate.</button>
    </template>
    <slot v-else></slot>
  </div>
</template>

<script setup>
import { useRouteContext } from '@fastify/vue/client'
const { actions, state } = useRouteContext()
</script>

// starters/react-typescript/src/client/layouts/auth.jsx
import { Suspense } from 'react'
import { useRouteContext } from '@fastify/react/client'

export default function Auth({ children }) {
  const { actions, state, snapshot } = useRouteContext()
  const authenticate = () => actions.authenticate(state)
  return (
    <Suspense>
      {snapshot.user.authenticated ? children : <Login onClick={() => authenticate()} />}
    </Suspense>
  )
}

function Login({ onClick }) {
  return (
    <>
      <p>This route needs authentication.</p>
      <button onClick={onClick}>Click this button to authenticate.</button>
    </>
  )
}
