// starters/vue-base/client/pages/index.vue
<template>
  <h1>{{ message }}</h1>
  <p><img :src="logo" /></p>
</template>

<script setup>
import logo from '/assets/logo.svg'

const message = 'Welcome to @fastify/vue!'
</script>

<script>
export function getMeta() {
  return {
    title: 'Welcome to @fastify/vue!',
  }
}
</script>

<style scoped>
img {
  width: 100%;
}
</style>

// starters/react-rsc/client/pages/index.jsx
import logo from '/assets/logo.svg'
import Examples from '/comp/examples.jsx'
import { useRouteContext } from '@fastify/react/client'

export function getMeta () {
  return {
    title: 'Welcome to @fastify/react!'
  }
}

export default function Index () {
  const { snapshot, state } = useRouteContext()
  if (import.meta.env.SSR) {
    // State is automatically hydrated on the client
    state.message = 'Welcome to @fastify/react!'
  }
  return (
    <>
      <img src={logo} />
      <h1>{snapshot.message}</h1>
      <Examples />
    </>
  )
}
