// examples/solid-hydration/client/views/index.jsx
import { For } from 'solid-js'
import { Link } from 'solid-app-router'

export default function Index ({ state }) {
  let input
  const [{ todoList }, { addItem }] = state
  return (
    <>
      <ul>
        <For each={todoList()}>{(item, i) =>
          <li>{item}</li>
        }</For>
      </ul>
      <div>
        <input ref={input} />
        <button onClick={() => {
          addItem(input.value)
          input.value = ''
        }}>Add</button>
      </div>
      <p>
        <Link href="/other">Go to another page</Link>
      </p>
    </>
  )
}

// examples/svelte-hydration/client/views/index.svelte
<script>
import { Link } from 'svelte-routing'
import { todoList } from '../state.js'

export let value

function addItem () {
  $todoList = [...$todoList, value]
  value = ''
}
</script>

<ul>
  {#each $todoList as item, i}
    <li>{item}</li>
  {/each}
  </ul>
<div>
  <input bind:value />
  <button on:click={addItem}>Add</button>
</div>
<p>
  <Link to="/other">Go to another page</Link>
</p>
