// examples/vue-vanilla/client/views/index.vue
<template>
	<ul>
		<li v-for="item in state.todoList">{{ item }}</li>
	</ul>
	<div>
	  <input v-model="item">
    <button @click="addItem">Add</button>
  </div>
  <p>
  	<router-link to="/other">Go to another page</router-link>
  </p>
</template>

<script>
import state from '/state'

export default {
  data: () => ({
  	item: '',
  	state,
  }),
  methods: {
		async addItem () {
     	this.state.todoList.push(this.item)
      this.item = ''
    }
  },
}
</script>

// examples/svelte-hydration/client/views/index.svelte
<script>
import { Link } from 'svelte-routing'
export let data = null
</script>

<ul>
  {#each data.todoList as item, i}
    <li>{item}</li>
  {/each}
  </ul>
<div>
  <!--input ref={input} /-->
  <!--button onClick={addItem}>Add</button-->
</div>
<p>
  <Link to="/other">Go to another page</Link>
</p>
