// examples/react-next-mini/client/pages/items/[id].jsx
import { Link } from 'react-router'

export async function getServerSideProps({ req, fetchJSON }) {
  const todoList = await fetchJSON("/api/todo-list");
  return { item: todoList[req.params.id] };
}

export default function Item ({ item }) {
  return (
    <>
      <p>{ item }</p>
      <p>
        <Link to="/">Go to the index</Link>
      </p>
    </>
  )
}

// examples/vue-next-mini/client/pages/items/nested/[id].vue
<script>
export async function getServerSideProps ({ req, ky }) {
  const todoList = await ky('api/todo-list').json()
  return { item: todoList[req.params.id] }
}
</script>

<template>
  <p>{{ $serverSideProps.item }}</p>
  <p>
    <router-link to="/"> Go to the index </router-link>
  </p>
</template>
