// examples/react-vanilla/client/base.jsx
import React, { Suspense, useContext, useState, useEffect } from 'react'
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import { StaticRouter } from 'react-router-dom/server'
import { Provider as StateProvider } from 'jotai'

import routes from './routes.js'
import { todoList } from './state.js'

const Router = import.meta.env.SSR ? StaticRouter : BrowserRouter

export function createApp (ctx, url) {
  return (
  	<StateProvider initialValues={[
  		[todoList, ctx.data.todoList],
  	]}>
	  	<Suspense>
		  	<Router location={url}>
			    <Routes>{
			      routes.map(({ path, component: Component }) => {
			        return <Route key={path} path={path} element={<Component />} />
			      })
			    }</Routes>
			  </Router>
			</Suspense>
		</StateProvider>
  )
}

// examples/solid-hydration/client/base.jsx
import { createContext, useContext, createSignal } from 'solid-js'
import { Router, Routes, Route } from 'solid-app-router'
import routes from './routes.js'

export function createApp ({ data }) {
  return (
    <StateProvider todoList={data.todoList}>
      <App />
    </StateProvider>
  )
}

const State = createContext()

export function StateProvider (props) {
  const [todoList, setTodoList] = createSignal(props.todoList)
  const state = [{ todoList }, {
    addItem (item) {
      setTodoList(todoList => [...todoList, item])
    }
  }]
  return (
    <State.Provider value={state}>
      {props.children}
    </State.Provider>
  );
}
export function App ({ data }) {
  return (
    <Router>
      <Routes>{
        routes.map(({ path, component: Component }) => {
          return <Route path={path} element={
            <Component state={useContext(State)} />
          } />
        })
      }</Routes>
    </Router>
  )
}
