// examples/solid/client/index.jsx
import { useContext, createSignal, For } from 'solid-js'
import ky from 'ky-universal'
import Context from '/entry/context.js'

export default function Index (props) {
	let input
  const { todoList: raw } = import.meta.env.SSR
    ? useContext(Context).data
    : window.hydration
  const [todoList, setTodoList] = createSignal(raw)
  const addItem = async () => {
    const json = { item: input.value }
    await ky.post('/add', { json }).json()
    setTodoList(list => [...list, input.value])
    input.value = ''
  }
  return (
    <>
      <ul>
      	<For each={todoList}>{(item) => <li>{item}</li>}</For>
      </ul>
      <input ref={input} />
      <button onClick={addItem}>Add</button>
    </>
  )
}

// examples/vue/client/index.vue
<template>
	<ul>
		<li v-for="item in todoList">{{ item }}</li>
	</ul>
	<input v-model="item">
  <button @click="addItem">Add</button>
</template>

<script>
import ky from 'ky-universal'
import { reactive, ref, useSSRContext } from 'vue'

export default {
	setup () {
		const { todoList: raw } = import.meta.env.SSR ? useSSRContext() : window.ssrContext
		const todoList = reactive(raw)
		const item = ref('')
		const addItem = async () => {
    	const json = { item: item.value }
      await ky.post('/add', { json }).json()
      todoList.push(item.value)
      item.value = ''
    }
    return { todoList, item, addItem }
   }
}
</script>
