// examples/vue-next-mini/client/pages/items/index.vue
<script>
export async function getServerSideProps({ ky }) {
  return {
    todoList: await ky('api/todo-list').json(),
  }
}
</script>

<template>
  <ul>
    <li v-for="(listItem, i) in $serverSideProps.todoList" :key="`item-${i}`">
      <router-link :to="`/items/${i}`">
        {{ listItem }}
      </router-link>
    </li>
  </ul>
  <p>
    <router-link to="/"> Go to the index </router-link>
  </p>
</template>

// examples/react-next/client/pages/items/index.jsx
import React from 'react'
import { Link } from 'react-router-dom'

export async function getServerSideProps ({ ky }) {
  return {
    todoList: await ky('api/todo-list').json()
  }
}

export default function ItemsIndex ({ todoList = [] }) {
  return (
    <>
      <ul>{
        todoList.map((item, i) => {
          return <li key={`item-${i}`}><Link to={`/items/${i}`}>{item}</Link></li>
        })
      }</ul>
      <p>
        <Link to="/">Go to the index</Link>
      </p>
    </>
  )
}
