// examples/react-base/views/index.jsx
import { Link } from 'react-router-dom'
import { useFastify } from 'fastify-vite-react/server'

export const path = '/'

export default function Index () {
  const fastify = useFastify()
  console.log(fastify)
  return (
    <>
      <h1>Index Page</h1>
      <p>Go to <Link to="/about">/about</Link></p>
    </>
  )
}

// examples/vue-base/views/index.vue
<template>
  <h1>Index Page</h1>
  <p><router-link to="/about">Go to /about</router-link></p>
</template>

<script>
import { useFastify } from 'fastify-vite-vue/server'

export const path = '/'

export default {
  async setup () {
    const fastify = useFastify()
    // console.log(typeof fastify)
    return
  }
}
</script>
