// starters/vue-kitchensink/client/pages/index.vue
<template>
  <h1>{{ message }}</h1>
  <p><img :src="logo" /></p>
  <ul class="columns-2">
    <li><router-link to="/using-data">/using-data</router-link> demonstrates how to 
    leverage the <code>getData()</code> function 
    and <code>useRouteContext()</code> to retrieve server data for a route.</li>
    <li><router-link to="/using-store">/using-store</router-link> demonstrates how to 
    retrieve server data and maintain it in the global state.</li>
    <li><router-link to="/using-auth">/using-auth</router-link> demonstrates how to 
    wrap a route in a custom layout component.</li>
    <li><router-link to="/client-only">/client-only</router-link> demonstrates how to set 
    up a route for rendering on the client only (disables SSR).</li>
    <li><router-link to="/server-only">/server-only</router-link> demonstrates how to set 
    up a route for rendering on the server only (sends no JavaScript).</li>
    <li><router-link to="/streaming">/streaming</router-link> demonstrates how to set 
    up a route for SSR in streaming mode.</li>
  </ul>
</template>

<script setup>
import { isServer, useRouteContext } from '/:core.js'
import logo from '/assets/logo.svg'

const { state } = useRouteContext()

if (isServer) {
  // State is automatically hydrated on the client
  state.message = 'Welcome to Fastify DX for Vue!'
}

const message = state.message
</script>

<script>
export function getMeta () {
  return {
    title: 'Welcome to Fastify DX!'
  }
}
</script>

// starters/react-kitchensink/client/pages/index.jsx
import logo from '/assets/logo.svg'
import { Link } from 'react-router-dom'
import { isServer, useRouteContext } from '/:core.jsx'

export function getMeta () {
  return {
    title: 'Welcome to Fastify DX!'
  }
}

export default function Index () {
  const { snapshot, state } = useRouteContext()
  if (isServer) {
    // State is automatically hydrated on the client
    state.message = 'Welcome to Fastify DX for React!'
  }
  return (
    <>
      <img src={logo} />
      <h1>{snapshot.message}</h1>
      <ul className="columns-2">
        <li><Link to="/using-data">/using-data</Link> demonstrates how to 
        leverage the <code>getData()</code> function 
        and <code>useRouteContext()</code> to retrieve server data for a route.</li>
        <li><Link to="/using-store">/using-store</Link> demonstrates how to 
        leverage the 
        automated <a href="https://github.com/pmndrs/valtio">Valtio</a> store 
        to retrieve server data for a route and maintain it in a global 
        state even after navigating to another route.</li>
        <li><Link to="/using-auth">/using-auth</Link> demonstrates how to 
        wrap a route in a custom layout component.</li>
        <li><Link to="/client-only">/client-only</Link> demonstrates how to set 
        up a route for rendering on the client only (disables SSR).</li>
        <li><Link to="/server-only">/server-only</Link> demonstrates how to set 
        up a route for rendering on the server only (sends no JavaScript).</li>
        <li><Link to="/streaming">/streaming</Link> demonstrates how to set 
        up a route for SSR in streaming mode.</li>
      </ul>
    </>
  )
}
