// packages/fastify-vite-react/base/entry/client.jsx
import ReactDOM from 'react-dom'
import { ContextProvider, hydrate } from 'fastify-vite-react/client.mjs'
import { createApp } from '@app/client.jsx'

const { App, router: Router } = createApp()

hydrate().then((hydration) => {
  ReactDOM.hydrate(
    <Router>
      <ContextProvider context={hydration}>
        {App()}
      </ContextProvider>
    </Router>,
    document.getElementById('app'),
  )
})

// packages/fastify-vite-solid/base/entry/client.jsx
import { hydrate as hydrateSolid } from 'solid-js/web'
import { ContextProvider, hydrate } from 'fastify-vite-solid/client.mjs'
import { createApp } from '@app/client.jsx'

const { App, routes, router: Router } = createApp()

hydrate().then(async (hydration) => {
  const app = App(await routes())
  hydrateSolid(
    <Router>
      <ContextProvider context={hydration}>
        {app}
      </ContextProvider>
    </Router>,
    document.getElementById('app'),
  )
})
