// starters/react-typescript/src/client/pages/index.tsx
import logo from '/assets/logo.svg'
import { Link } from 'react-router'
import { useRouteContext } from '@fastify/react/client'

export function getMeta () {
  return {
    title: 'Welcome to @fastify/react!'
  }
}

export default function Index () {
  const { snapshot, state } = useRouteContext()
  if (import.meta.env.SSR) {
    // State is automatically hydrated on the client
    state.message = 'Welcome to @fastify/react!'
  }
  return (
    <>
      <img src={logo} />
      <h1>{snapshot.message}</h1>
      <ul className="columns-2">
        <li><Link to="/using-data">/using-data</Link> — isomorphic data fetching.</li>
        <li><Link to="/using-store">/using-store</Link> — integrated <a href="https://github.com/pmndrs/valtio">Valtio</a> store.</li>
        <li><Link to="/using-auth">/using-auth</Link> — <b>custom layout</b>.</li>
        <li><Link to="/form/123">/form/123</Link> — <code>POST</code> to dynamic route.</li>
        <li><Link to="/actions/data">/actions/data</Link> — inline <code>GET</code> handler.</li>
        <li><Link to="/actions/form">/actions/form</Link> — inline <code>POST</code> handler.</li>
        <li><Link to="/client-only">/client-only</Link> — <b>disabling</b> SSR.</li>
        <li><Link to="/server-only">/server-only</Link> — <code>0kb</code> JavaScript.</li>
        <li><Link to="/streaming">/streaming</Link> — <b>streaming</b> SSR.</li>
        <li><Link to="/wildcard/another/one">/wildcard/another/one</Link> — <b>wildcard route matching</b> <code>/wildcard/*</code></li>
      </ul>
    </>
  )
}

// starters/vue-typescript/src/client/pages/index.vue
<template>
  <h1>{{ message }}</h1>
  <p><img :src="logo" /></p>
  <ul class="columns-2">
    <li>
      <router-link to="/using-data">/using-data</router-link> — <b>isomorphic data fetching</b>.
    </li>
    <li>
      <router-link to="/using-store">/using-store</router-link> — <b>universal</b>
      <code>reactive()</code> stores.
    </li>
    <li><router-link to="/using-auth">/using-auth</router-link> — <b>custom layout</b>.</li>
    <li>
      <router-link to="/form/123">/form/123</router-link> — <code>POST</code> to dynamic route.
    </li>
    <li><router-link to="/client-only">/client-only</router-link> — <b>disabling</b> SSR.</li>
    <li>
      <router-link to="/server-only">/server-only</router-link> — <code>0kb</code> JavaScript.
    </li>
    <li><router-link to="/streaming">/streaming</router-link> — <b>streaming</b> SSR.</li>
    <li>
      <router-link to="/wildcard/another/one">/wildcard/another/one</router-link> —
      <b>wildcard route matching</b> <code>/wildcard/*</code>
    </li>
  </ul>
</template>

<script setup>
import { useState } from '$app/hooks'
import logo from '/assets/logo.svg'

const state = useState()

if (import.meta.env.SSR) {
  // State is automatically hydrated on the client
  state.message = 'Welcome to @fastify/vue!'
}

const message = state.message
</script>

<script>
export function getMeta () {
  return {
    title: 'Welcome to @fastify/vue!'
  }
}
</script>

<style>
.dummy {
  color: black;
}
</style>
