// examples/react-base/views/index.jsx
import { Link } from 'react-router-dom'
import { useFastify } from 'fastify-vite-react/server'

export const path = '/'

export default function Index () {
  const fastify = useFastify()
  console.log(fastify)
  return (
    <>
      <h1>Index Page</h1>
      <p>Go to <Link to="/about">/about</Link></p>
    </>
  )
}

// examples/vue-islands/views/index.vue
<template>
	<p>Test</p>
</template>

<script>
// import island from './island.vue'
import { useFastify } from 'fastify-vite-vue/server'

export default {
	async setup() {
		const fastify = useFastify()
		const island = await fastify.vite.render('header')
		console.log(island)
	}
	// components: { island },
}
</script>
