// starters/react-kitchensink/client/root.jsx
import 'virtual:uno.css'
import { Suspense } from 'react'
import { Routes, Route } from 'react-router-dom'
import { Router, AppRoute } from '/:core.jsx'

export default function Root ({ url, routes, head, ctxHydration, routeMap }) {
  return (
    <Suspense>
      <Router location={url}>
        <Routes>{
          routes.map(({ path, component: Component }) =>
            <Route
              key={path}
              path={path}
              element={
                <AppRoute
                  head={head}
                  ctxHydration={ctxHydration}
                  ctx={routeMap[path]}>
                  <Component />
                </AppRoute>
              } />,
          )
        }</Routes>
      </Router>
    </Suspense>
  )
}

// starters/vue-kitchensink/client/root.vue
<script>
import 'uno.css'
</script>

<script setup>
import Layout from '/:layout.vue'
</script>

<template>
  <router-view v-slot="{ Component }">
    <template v-if="$isServer">
      <Layout>
        <component
          :is="Component"
          :key="$route.path"
        />
      </Layout>
    </template>
    <Suspense v-else>
      <Layout>
        <component
          :is="Component"
          :key="$route.path"
        />
      </Layout>
    </Suspense>
  </router-view>
</template>
